spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
  data:
    web:
      pageable:
        max-page-size: 100000
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd HH:mm:ss"

  datasource:
    url: jdbc:mysql://192.168.0.6:3306/p4thdb
    username: p4th
    password: p4th12!@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size : 10
      connectionTimeout : 120000
      idleTimeout : 1800000
      maxLifetime: 28797000       # 28797초 (MySQL wait_timeout보다 3초 짧게 설정)
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true

  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  paths-to-match:
#    - /v1/**
  default-flat-param-object: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO

p4th:
  jwt:
    secret: "p4th_Secret_Key_20250203_p4th_Secret_Key_20250203"